version: '3'

services:
  geoserver:
      image: cartoview/geoserver_docker:tomcat-alpine
      volumes:
        - ./geoserver/data:/geoserver_data
      ports:
        - "8080:8080"
      restart: unless-stopped
      user: root
