version: '3'

services:
  geoserver:
      image: cartoview/geoserver_docker:jetty
      volumes:
        - ./webapps:/geoserver_data
      ports:
        - "8080:8080"
      restart: unless-stopped
      user: root
