version: '3'

services:
  geoserver:
      image: cartoview/tomcat_docker:latest
      volumes:
        - ./webapps:/usr/local/tomcat/webapps
      ports:
        - "8080:8080"
      restart: unless-stopped
      user: root
